modLoader="javafml"
loaderVersion="[28,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/jsburger/Architects-Palette/issues"

[[mods]]
    modId="architects_palette"
    namespace="architects_palette"
    version="1.1.2"
    displayName="Architect's Palette"
    authors="Snakeblock, THX, Smash Brothers, Orisghost, Mista Jub, Jsburg"
    description='''A mod that adds new stylish and unique building blocks'''
    displayURL=""
    [[dependencies.architects_palette]]
        modId="forge"
        mandatory=true
        versionRange="[${forge_version},)"
        ordering="NONE"